### ISSUE TITLE
Small fix in data/bin/make_data.py

### ISSUE THREAD

**Issue by hrishim** [sanskrit/data#3]
I ran into the issue below when installing vidyut-cheda 

OS: Ventura 12.0.1 Machine: Intel Macbook 
Python version: 3.8.11

The install script in vidyut-cheda checks out this repository and executes data/bin/make_data.py 

make_data.py failed for me with 

```
hrishi@Mumukshu vidyut-cheda % ./scripts/install.sh 
rm: data/: No such file or directory
Cloning into 'data-git'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 63 (delta 2), reused 25 (delta 1), pack-reused 0
Receiving objects: 100% (63/63), 1.48 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Traceback (most recent call last):
  File "data-git/bin/make_data.py", line 58, in <module>
    def cat(in_paths, out_path, headers: list[str]):
TypeError: 'type' object is not subscriptable
```

I fixed it by changing

```
def cat(in_paths, out_path, headers: list[str]):
```

to

```
from typing import List

def cat(in_paths, out_path, headers: List[str]):
```

Alternatively skip that type hint altogether. None of the other functions have typehints. 

Filing as an issue because I followed install.sh and deleted the my local version of the data/ repo. Sorry

**Comment by akprasad** [comment]
Fixed -- thanks!
